# Generated by Django 5.2.9 on 2026-01-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Student', 'Student'), ('Staff', 'Staff'), ('Principal', 'Principal'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
