# Generated by Django 5.2.9 on 2026-01-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_announcement_class_grade_attendance_classenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='e.g., Computer Science', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, help_text='e.g., Science, Commerce, Arts', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, help_text='e.g., 10th Grade, BSc Year 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, help_text='e.g., 2024, Freshman', max_length=20, null=True),
        ),
    ]
