# Generated by Django 5.2.9 on 2026-01-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_department_user_stream_user_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_classes',
            field=models.TextField(blank=True, help_text='Classes assigned to teach', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Years of teaching experience', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g., M.Sc Physics, B.Ed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subject_expertise',
            field=models.CharField(blank=True, help_text='e.g., Mathematics, Physics', max_length=200, null=True),
        ),
    ]
