# Generated by Django 5.2.9 on 2026-01-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_assigned_classes_user_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Has user completed their profile details'),
        ),
    ]
